# Site Settings
title: Vu Quang Thinh
description: "Vu Quang Thinh's Resume"
url: 'http://agiletech.vn'
baseurl: 'https://agiletechvn.github.io' #change it according to your repository name
about: True # set to False or comment line if you want to remove the "How to use?" in the sidebar


# Enable one of these styles by removing #. Style will be applied only after restarting the build or serve.
#style: styles-2
#style: styles-3
#style: styles-4
#style: styles-5
#style: styles-6


#Profile information
name: Vu Quang Thinh
tagline: Full Stack Developer
pic: quangthinh.jpg  #place a 100x100 picture inside /assets/images/ folder and provide the name of the file below
summary: "I'm a fullstack developer of Agiletech Viet Nam. I love coding and solve hard problem. have more than 4 years of work
experience in any positions. Side by side I love guitar and solving rubik.
<br />
You can view more about <a href="http://agiletech.vn" target="_blank">Agiletech Viet Nam</a>."

#sidebar links
email: thinh@agiltech.vn
phone: _841695708005
website: agiletech.vn #do not add http://
linkedin: vuquangthinh
github: vuquangthinh
twitter: '@vuquangthinh'
#Update all the sections by editing the files inside _data folder.

# uncomment the next line, if you want the education section displayed in main instead of the sidebar
#education_in_main: True

# Tracker
analytics: UA-119187154-1

# Build settings
encoding: "utf-8"
compress_html: # - http://jch.penibelst.de/
  clippings: all
  ignore:
    envs: development
